# Generated by Django 4.2.5 on 2023-12-13 01:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('note_taking', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='note',
            name='tags',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
    ]
